CREATE TABLE tb_heartbeat_log (
  id integer NOT NULL,
  hospital_id integer not null,
  period varchar(100) NOT NULL,
  create_time datetime NOT NULL,
  update_time timestamp NOT NULL,
  PRIMARY KEY (id)
);
CREATE SEQUENCE tb_heartbeat_log_seq START WITH 100 INCREMENT BY 1;

CREATE TABLE tb_order_log (
  id integer NOT NULL,
  order_id integer NOT NULL,
  result_code integer not NULL,
  result_desc varchar(100) not NULL,
  operator varchar(100) not NULL,
  create_time datetime NOT NULL,
  update_time timestamp NOT NULL,
  hospital_id integer ,
  PRIMARY KEY (id)
);

CREATE SEQUENCE tb_order_log_seq START WITH 100 INCREMENT BY 1;

CREATE TABLE tb_upgrade_message (
  id integer NOT NULL,
  hospital_id integer,
  curr_version varchar(100),
  new_version varchar(100),
  package_file varchar(1000),
  status integer not null,
  upgrade_time datetime NOT NULL,
  PRIMARY KEY (id)
);

CREATE SEQUENCE tb_upgrade_message_seq START WITH 100 INCREMENT BY 1;

CREATE TABLE tb_sync_exam_report (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  gmt_created datetime DEFAULT NULL,
  gmt_modified datetime DEFAULT NULL,
  hospital_id integer DEFAULT NULL,
  report_no varchar(32) DEFAULT NULL,
  order_num varchar(32) DEFAULT NULL,
  idcard varchar(20) DEFAULT NULL,
  exam_time varchar(32) DEFAULT NULL,
  report_time varchar(32) DEFAULT NULL,
  mobile varchar(32) DEFAULT NULL,
  company_name varchar(50) DEFAULT NULL,
  state varchar(32) DEFAULT NULL,
  report_context text,
  PRIMARY KEY (id)
);

create table tb_his_info(
	hospital_id integer,
	his_name varchar(50) default null,
	engine_name varchar(50) default null,
	gmt_created datetime DEFAULT NULL,
    gmt_modified datetime DEFAULT NULL, 
	primary key (hospital_id)
);


CREATE TABLE tb_mediator_agent_task (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null,
  gmt_created datetime DEFAULT NULL,
  gmt_modified datetime DEFAULT NULL,
  hospital_id integer DEFAULT NULL,
  task_cmd varchar(32) DEFAULT NULL,
  task_params varchar(32) DEFAULT NULL,
  init integer DEFAULT NULL,
  status integer DEFAULT 1,
  task_bean_name varchar(100) null,
  crontab_expression varchar(100) null,
  province_id int
);

--SET DATABASE EVENT LOG SQL LEVEL 3;
CREATE TABLE tb_mediator_his_company (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null,
  gmt_created datetime DEFAULT NULL,
  gmt_modified datetime DEFAULT NULL,
   hospital_id integer DEFAULT NULL,
  my_company_id integer DEFAULT NULL,
  his_company_code varchar(32) DEFAULT NULL,
  his_company_name varchar(32) DEFAULT NULL,
  his_company_status varchar(32) DEFAULT NULL,
  creator varchar(32) DEFAULT NULL,
  refresh varchar(32) DEFAULT NULL,
  is_deleted integer DEFAULT NULL
);

CREATE TABLE tb_mediator_meal_sync_log (
	meal_id integer not null,
	his_meal_id varchar(200) default null,
	hospital_id integer not null,
	company_id integer default null,
	his_name varchar(200) default null,
	status integer not null,
	create_time datetime default null,
	update_time timestamp default null,
	PRIMARY KEY (meal_id)
);


CREATE TABLE tb_mediator_order_export_his (
  export_id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null,
  order_id integer NOT NULL,
  hospital_id integer NOT NULL,
  create_time datetime NOT NULL,
  update_time datetime DEFAULT NULL,
  is_export integer DEFAULT 0,
  export_type integer DEFAULT 0,
  sequence integer DEFAULT 0,
  order_num varchar(300),
  exam_date datetime,
  account_id integer,
  name varchar(300),
  PRIMARY KEY (export_id)
);

CREATE TABLE tb_mediator_order_print_hist (
  order_id integer NOT NULL,
  order_num varchar(50) NOT NULL,
  hospital_id integer NOT NULL,
  create_time datetime,
  update_time datetime,
  print_status integer DEFAULT 0,
  is_print integer DEFAULT 0,
  add_his_queue integer DEFAULT 0,
  PRIMARY KEY (order_id)
);

CREATE TABLE tb_mediator_order_statistics (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null,
  gmt_created datetime,
  gmt_modified datetime,
  hospital_id integer ,
  task_id integer,
  statistics_item varchar(200) ,
  param varchar(200) ,
  result varchar(2000),
  format varchar(200),
  PRIMARY KEY (id)
);

CREATE TABLE tb_mediator_agent_task_config (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 1) not null,
  gmt_created datetime,
  gmt_modified datetime,
  task_cmd varchar(100),
  task_name varchar(200),
  sequence integer,
  default_task_bean_name varchar(100),
  default_task_params varchar(2000),
  default_crontab_expression varchar(100),
  PRIMARY KEY (id)
);

create table tb_gray_setting(
	id integer GENERATED BY DEFAULT AS IDENTITY,
	hospital_id          integer,
	status integer,
	create_time datetime,
	update_time datetime
);


CREATE TABLE tb_mediator_security_setting(
id integer GENERATED BY DEFAULT AS IDENTITY,
gmt_created datetime ,
gmt_modified datetime,
hospital_id integer,
version integer
);

CREATE TABLE tb_mediator_genericpeservice_task(
	id integer GENERATED BY DEFAULT AS IDENTITY,
	hospital_id integer,
	task_name varchar(100),
	task_params VARCHAR(1024),
	task_switch integer,
	crontab_expression VARCHAR(128),
	gmt_created datetime ,
	gmt_modified datetime
);
